services:
  redis:
    container_name: redis_notification
    image: redis:alpine3.20
    ports:
      - "6379:6379"
    network_mode: bridge
    restart: unless-stopped
  mail-server:
    container_name: mail_server
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8025:8025" # HTTP / UI
      - "1025:1025" # SMTP
    network_mode: bridge
    restart: unless-stopped
