services:
  notification:
    container_name: notification
    build:
      context: .
      target: final
    environment:
      - SERVER_PORT=80
      - MAIL_FROM=no-reply@example.com
      - SMTP_HOST=mail_server
      - SMTP_PORT=1025
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8080:80"
    networks:
      - notification-network
    restart: unless-stopped
    healthcheck:
      test: wget --spider --tries=1 --timeout=10 http://localhost:80/healthz || exit 1
      interval: 30s
      retries: 5
      start_period: 15s
      timeout: 10s
  redis:
    container_name: redis_notification
    image: redis:alpine3.20
    ports:
      - "6379:6379"
    networks:
      - notification-network
    restart: unless-stopped
  mail-server:
    container_name: mail_server
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8025:8025" # HTTP / UI
      - "1025:1025" # SMTP
    networks:
      - notification-network
    restart: unless-stopped

networks:
  notification-network:
    driver: bridge
