// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "notification/internal/domain"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// NotificationSender is an autogenerated mock type for the NotificationSender type
type NotificationSender struct {
	mock.Mock
}

// Send provides a mock function with given fields: ctx, userID, msg, notificationType
func (_m *NotificationSender) Send(ctx context.Context, userID string, msg string, notificationType domain.NotificationType) (time.Duration, error) {
	ret := _m.Called(ctx, userID, msg, notificationType)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 time.Duration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, domain.NotificationType) (time.Duration, error)); ok {
		return rf(ctx, userID, msg, notificationType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, domain.NotificationType) time.Duration); ok {
		r0 = rf(ctx, userID, msg, notificationType)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, domain.NotificationType) error); ok {
		r1 = rf(ctx, userID, msg, notificationType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewNotificationSender creates a new instance of NotificationSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationSender {
	mock := &NotificationSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
