// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "notification/internal/domain"

	mock "github.com/stretchr/testify/mock"

	service "notification/internal/service"
)

// RateLimitHandler is an autogenerated mock type for the RateLimitHandler type
type RateLimitHandler struct {
	mock.Mock
}

// LockIfAvailable provides a mock function with given fields: ctx, userID, notificationType
func (_m *RateLimitHandler) LockIfAvailable(ctx context.Context, userID string, notificationType domain.NotificationType) (*service.LockResult, error) {
	ret := _m.Called(ctx, userID, notificationType)

	if len(ret) == 0 {
		panic("no return value specified for LockIfAvailable")
	}

	var r0 *service.LockResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.NotificationType) (*service.LockResult, error)); ok {
		return rf(ctx, userID, notificationType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.NotificationType) *service.LockResult); ok {
		r0 = rf(ctx, userID, notificationType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.LockResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.NotificationType) error); ok {
		r1 = rf(ctx, userID, notificationType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRateLimitHandler creates a new instance of RateLimitHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRateLimitHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *RateLimitHandler {
	mock := &RateLimitHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
