// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"
	service "notification/internal/service"

	mock "github.com/stretchr/testify/mock"
)

// RateLimitHandler is an autogenerated mock type for the RateLimitHandler type
type RateLimitHandler struct {
	mock.Mock
}

// Check provides a mock function with given fields: ctx, userID, notificationType
func (_m *RateLimitHandler) Check(ctx context.Context, userID string, notificationType service.NotificationType) (bool, error) {
	ret := _m.Called(ctx, userID, notificationType)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, service.NotificationType) (bool, error)); ok {
		return rf(ctx, userID, notificationType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, service.NotificationType) bool); ok {
		r0 = rf(ctx, userID, notificationType)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, service.NotificationType) error); ok {
		r1 = rf(ctx, userID, notificationType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IncrementCount provides a mock function with given fields: ctx, userID, notificationType
func (_m *RateLimitHandler) IncrementCount(ctx context.Context, userID string, notificationType service.NotificationType) error {
	ret := _m.Called(ctx, userID, notificationType)

	if len(ret) == 0 {
		panic("no return value specified for IncrementCount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, service.NotificationType) error); ok {
		r0 = rf(ctx, userID, notificationType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRateLimitHandler creates a new instance of RateLimitHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRateLimitHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *RateLimitHandler {
	mock := &RateLimitHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
