// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	infra "notification/internal/infra"

	mock "github.com/stretchr/testify/mock"
)

// RedisCacheOption is an autogenerated mock type for the RedisCacheOption type
type RedisCacheOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: r
func (_m *RedisCacheOption) Execute(r *infra.RedisCache) {
	_m.Called(r)
}

// NewRedisCacheOption creates a new instance of RedisCacheOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRedisCacheOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *RedisCacheOption {
	mock := &RedisCacheOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
