// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	infra "notification/internal/infra"

	mock "github.com/stretchr/testify/mock"
)

// SMTPMailerOption is an autogenerated mock type for the SMTPMailerOption type
type SMTPMailerOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *SMTPMailerOption) Execute(_a0 *infra.SMTPMailer) {
	_m.Called(_a0)
}

// NewSMTPMailerOption creates a new instance of SMTPMailerOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSMTPMailerOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *SMTPMailerOption {
	mock := &SMTPMailerOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
