// Package api GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2024-10-13 15:54:47.415815852 -0300 -03 m=+0.901595414
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Notification API Support",
            "email": "foo@bar.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/send": {
            "post": {
                "description": "Sends a notification message",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notification"
                ],
                "summary": "Send a notification message",
                "parameters": [
                    {
                        "description": "Notification object to be sent",
                        "name": "notification",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.Notification"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.Notification": {
            "type": "object",
            "properties": {
                "correlationId": {
                    "description": "CorrelationID is the ID used for correlating the notification message with different microservices,\nincluding the sender microservice, which means it's treated as a universally unique identifier.",
                    "type": "string"
                },
                "message": {
                    "description": "Message is the message content of the notification.",
                    "type": "string"
                },
                "type": {
                    "description": "Type is the notification type.",
                    "type": "string"
                },
                "userId": {
                    "description": "UserID is the ID corresponding to the user the notification is meant to be sent to.",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "notification",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Notification API",
	Description:      "A really nice description",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
